### PR TITLE
Fixes for double-freeing native tensor handles.

### PR DESCRIPTION
**Pull request by NiklasGustafsson**
This PR fixes three instances of native tensor handles being freed more than once, causing access violations.

It includes the fix surfaced in PR #316.

### CODE REVIEW

**Comment by NiklasGustafsson** [comment]
@lostmsu, I tried to add you as a reviewer, but your name didn't pop up on the list.

**Review by lostmsu — APPROVED** [review]
Looks good to me

**Comment by lostmsu** [comment]
Do your tests for the custom module without the fix? I wonder why you had to replace the original one.

**Comment by NiklasGustafsson** [comment]
Yeah, I copied your test to debug it and understand exactly how it went wrong, then I copied your fix, etc.

**Pull request merged**
