### PR TITLE
Prepare for 2.2.0 upgrade.

### PR DESCRIPTION
**Pull request by NiklasGustafsson**

### CODE REVIEW

**Comment by NiklasGustafsson** [comment]
@shaltielshmid -- do you work on Linux at all? Are you a CMake expert?

I ask, because I'm having trouble with this upgraded. It's failing to configure the Makefiles with errors in the downloaded libtorch CMake files. There are some slight changes from v2.1.0, but they are in the downloaded files, which the build can't touch.

If there's anyone else who can help, please let me know.

Here's the recurring error:

```
-- Detecting CXX compile features - done
  CMake Error at /__w/1/s/bin/obj/AnyCPU.Release/libtorch-cpu/libtorch-cxx11-abi-shared-with-deps-2.2.0cpu/libtorch/share/cmake/Caffe2/public/mkl.cmake:7 (target_include_directories):
    Cannot specify include directories for imported target "caffe2::mkl".
  Call Stack (most recent call first):
    /__w/1/s/bin/obj/AnyCPU.Release/libtorch-cpu/libtorch-cxx11-abi-shared-with-deps-2.2.0cpu/libtorch/share/cmake/Caffe2/Caffe2Config.cmake:105 (include)
    /__w/1/s/bin/obj/AnyCPU.Release/libtorch-cpu/libtorch-cxx11-abi-shared-with-deps-2.2.0cpu/libtorch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
    LibTorchSharp/CMakeLists.txt:7 (find_package)
  
  
  CMake Error at /__w/1/s/bin/obj/AnyCPU.Release/libtorch-cpu/libtorch-cxx11-abi-shared-with-deps-2.2.0cpu/libtorch/share/cmake/Caffe2/public/mkl.cmake:8 (target_link_libraries):
    Cannot specify link libraries for target "caffe2::mkl" which is not built
    by this project.
  Call Stack (most recent call first):
    /__w/1/s/bin/obj/AnyCPU.Release/libtorch-cpu/libtorch-cxx11-abi-shared-with-deps-2.2.0cpu/libtorch/share/cmake/Caffe2/Caffe2Config.cmake:105 (include)
    /__w/1/s/bin/obj/AnyCPU.Release/libtorch-cpu/libtorch-cxx11-abi-shared-with-deps-2.2.0cpu/libtorch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
    LibTorchSharp/CMakeLists.txt:7 (find_package)
  
  
  -- Configuring incomplete, errors occurred!
```

**Comment by shaltielshmid** [comment]
> @shaltielshmid -- do you work on Linux at all? Are you a CMake expert?

I do work on linux, but I'm far from a CMake expert. I'll give this a shot :)

Right now I'm getting this error:

```
  [  4%] Building CXX object LibTorchSharp/CMakeFiles/LibTorchSharp.dir/cifar10.cpp.o
  In file included from <built-in>:421:
<command line>(11,9): error G1AFDF199: '_GLIBCXX_USE_CXX11_ABI' macro redefined [-Werror,-Wmacro-redefined] [/mnt/d/Shaltiel/MyGitRepo/TorchSharp/src/Native/build.proj]
  #define _GLIBCXX_USE_CXX11_ABI 1
          ^
  <command line>:6:9: note: previous definition is here
  #define _GLIBCXX_USE_CXX11_ABI 0
          ^
  1 error generated.
  make[2]: *** [LibTorchSharp/CMakeFiles/LibTorchSharp.dir/build.make:76: LibTorchSharp/CMakeFiles/LibTorchSharp.dir/cifar10.cpp.o] Error 1
  make[1]: *** [CMakeFiles/Makefile2:98: LibTorchSharp/CMakeFiles/LibTorchSharp.dir/all] Error 2
  make: *** [Makefile:136: all] Error 2 
```

**Comment by NiklasGustafsson** [comment]
I have a fix for that one coming... I got farther on my own, but haven't seen it work in CI/CD yet. No need to spend time on this right now!

**Comment by shaltielshmid** [comment]
> I have a fix for that one coming... I got farther on my own, but haven't seen it work in CI/CD yet. No need to spend time on this right now!

OK! Feel free to tag me in if you want to split the work at any point :)

**Comment by NiklasGustafsson** [comment]
I have a clean build on my WSL-based Ubuntu. Right now, the CI/CD build doesn't even get to CMake, it fails when it verifies that Clang has been installed. This has been an ongoing and intermittent problem for a while. There's a check in build.sh that fails:

```
# Set up the environment to be used for building with clang.
if command -v "clang-6.0" > /dev/null 2>&1; then
    export CC="$(command -v clang-6.0)"
    export CXX="$(command -v clang++-6.0)"
elif command -v "clang-5.0" > /dev/null 2>&1; then
    export CC="$(command -v clang-5.0)"
    export CXX="$(command -v clang++-5.0)"
elif command -v clang > /dev/null 2>&1; then
    export CC="$(command -v clang)"
    export CXX="$(command -v clang++)"
else
    echo "Unable to find Clang Compiler"
    echo "Install clang-6.0 or clang-5.0"
    exit 1
fi

```

**Comment by shaltielshmid** [comment]
Yes, I've noticed that. 
What is the reason that the build uses clang-6.0 and not the latest (I think 14.0)?

I have it (the previous version) building on my WSL-based Ubuntu 22.04 with the latest clang.

**Comment by NiklasGustafsson** [comment]
> Yes, I've noticed that. What is the reason that the build uses clang-6.0 and not the latest (I think 14.0)?
> 
> I have it (the previous version) building on my WSL-based Ubuntu 22.04 with the latest clang.

When I do 'apt install clang-7.0' the version number I get is 14.0

**Comment by shaltielshmid** [comment]
Does running just `apt install clang` make a difference?

**Comment by NiklasGustafsson** [comment]
Okay, my edits get past the problem with the redefinition. Now, it's like before -- CMake fails in Azure, but not on my local machine.

**Comment by NiklasGustafsson** [comment]
Interesting... On MacOS, the cmake version is 3.28. On Ubuntu, cmake is 3.10.2, which is very old. On my machine, it's 3.22.1.  I'll have to look at this tomorrow. So far, one day wasted.

**Comment by NiklasGustafsson** [comment]
Closing to test with my own repo. Will open new PR for the v2.2.0 upgrade when everything works.

**Pull request closed without merging**
