### PR TITLE
[WIP] Bump LibTorch to 1.9.0

### PR DESCRIPTION
**Pull request by dsyme**
This bumps LibTorch to 1.9.0 

* [x] Linux CPU LibTorch ZIPs downloaded and SHA generated
* [x] Mac CPU LibTorch ZIPs downloaded and SHA generated
* [x] Windows Debug CPU LibTorch ZIPs downloaded and SHA generated
* [x] Windows Release CPU LibTorch ZIPs downloaded and SHA generated
* [x] CPU binary lists updated
* [x] Linux CUDA LibTorch ZIPs downloaded and SHA generated
* [x] Windows Debug CUDA LibTorch ZIPs downloaded and SHA generated
* [x] Windows Debug CUDA binary lists updated 
* [x] Windows Release CUDA LibTorch ZIPs downloaded and SHA generated
* [x] Windows Release CUDA binary lists updated 
* [x] Test locally this builds on Windows
* [x] Get it green
* [ ] Solve the inevitable problems with package sizes
* [ ] Publish new packages on integration to master

### CODE REVIEW

**Comment by dsyme** [comment]
This will need solving, perhaps we do it as part of this: https://github.com/xamarin/TorchSharp/issues/276

**Comment by dsyme** [comment]
Problems where the PyTorch API has changed, `adaptive_avg_pool3d_backward` removed of renamed
```
E:\GitHub\dsyme\TorchSharp\src\Native\LibTorchSharp\THSTensorConv.cpp(40,1): error C2039: 'adaptive_avg_pool3d_backward': is not a member of 'torch' [E:\GitHub\dsyme\TorchSharp\bin\obj\x64.Debug\Native\LibTorchSharp\LibTorchSharp.vcxproj] [E:\GitHub\dsyme\TorchSharp\src\Native\build.proj]
E:\GitHub\dsyme\TorchSharp\src\Native\LibTorchSharp\THSTensorConv.cpp(40,1): error C3861: 'adaptive_avg_pool3d_backward': identifier not found [E:\GitHub\dsyme\TorchSharp\bin\obj\x64.Debug\Native\LibTorchSharp\LibTorchSharp.vcxproj] [E:\GitHub\dsyme\TorchSharp\src\Native\build.proj]
E:\GitHub\dsyme\TorchSharp\src\Native\LibTorchSharp\THSTensorConv.cpp(40,1): error C2039: 'adaptive_avg_pool3d_backward': is not a member of 'torch' [E:\GitHub\dsyme\TorchSharp\bin\obj\x64.Debug\Native\LibTorchSharp\LibTorchSharp.vcxproj] [E:\GitHub\dsyme\TorchSharp\src\Native\build.proj]
E:\GitHub\dsyme\TorchSharp\src\Native\LibTorchSharp\THSTensorConv.cpp(40,1): error C3861: 'adaptive_avg_pool3d_backward': identifier not found [E:\GitHub\dsyme\TorchSharp\bin\obj\x64.Debug\Native\LibTorchSharp\LibTorchSharp.vcxproj] [E:\GitHub\dsyme\TorchSharp\src\Native\build.proj]
E:\GitHub\dsyme\TorchSharp\src\Native\build.proj(53,5): error MSB3073: The command ""E:\GitHub\dsyme\TorchSharp\src\Native\build.cmd" Debug x64 --libtorchpath E:\GitHub\dsyme\TorchSharp\bin/obj/AnyCPU.Debug\libtorch-cpu\libtorch-win-shared-with-deps-debug-1.9.0cpu\libtorch\share\cmake\Torch" exited with code 1.
    0 Warning(s)
    5 Error(s)

```

**Comment by NiklasGustafsson** [comment]
Should we create a new branch libtorch-1.9.0 here to keep things out of master until it's baked?

**Comment by dsyme** [comment]
> Should we create a new branch libtorch-1.9.0 here to keep things out of master until it's baked? I can take care of the API changes, if you look at the packaging issues (since you know NuGet better than I do).

I've fixed the API change.   If we get it green we can integrate straight to master - we sort of need to do that to get the actual native packages built (a very tedious process) - I don't really want to try to do that in a separate branch I think.  LibTorch has been pretty good about backwards compat.

We can then do the API additions incrementally after that.

**Comment by dsyme** [comment]
Note that every release of LibTorch things get bigger and Bigger and BIGGER.  

* With 1.9.0 they're now at 3GB ZIP for CUDA (4GB for Windows Debug CUDA).
* There are individual DLLs/.so with size up to 2.5GB 

We may well hit size limitations on the CI servers with this update.

I guess I may try and give it a go to build the new native packages in a branch. Currently we look for 'master' explicitly here: https://github.com/xamarin/TorchSharp/blob/master/azure-pipelines.yml#L71.  I might hardwire a path

One reason I do it only in master is because the native package builds use a lot of storage resources on the CI system and I have to go and delete off the results manually.   This is because we're building out of a regular Azure DevOps account (associated with my "donsyme" account).  Ideally we'd build out of a Microsoft-account with extra resources.  I switched to a regular account in the middle of trying to work out what was going on with large-package woes, just to see if it was some size limitation associated with the Microsoft build account we were using, and ended up sticking with it since I could rely on the exact documented resources as shown on the Azure pages

**Comment by dsyme** [comment]
Good to see things going green on this now.  The hard part now will be the package builds.

**Comment by dsyme** [comment]
I will merge to master once the last SHA is availble.

You should `clean -xfd` and rebuild once it's in.

**Comment by dsyme** [comment]
Ubuntu builds are taking a really long time because packages.microsoft.com is still having trouble, serving installation dependency content very slowly.  Someone was reporting 28kbps, dialup modem time :)

**Comment by NiklasGustafsson** [comment]
> Someone was reporting 28kbps, dialup modem time :)

I'm old enough to remember when 9600 baud dial-up was really rockin' it. Those were the days... :-)

**Comment by dsyme** [comment]
I will do further work on packages directly

**Pull request merged**
